### ISSUE TITLE
Port scripting engine to netstandard

### ISSUE THREAD

**Issue by yvesgoeleven** [MessageHandler/MessageHandler.Runtime#14]
Current code in

https://github.com/MessageHandler/MessageHandler.Runtime/tree/master/src/runtime/DynamicConfiguration/Roslyn

Base type should move to 

https://github.com/MessageHandler/MessageHandler.Runtime/tree/master/src/scripting

Roslyn implementation should go to

https://github.com/MessageHandler/MessageHandler.Runtime/tree/master/src/scripting.roslyn

**Comment by yvesgoeleven** [comment]
@SeanFeldman can you have a look at why all xunit tests are inconclusive?

**Comment by SeanFeldman** [comment]
Merged a fix. Closing this one.
