### ISSUE TITLE
Port IOC container to netstandard library

### ISSUE THREAD

**Issue by yvesgoeleven** [MessageHandler/MessageHandler.Runtime#6]
Current code is in 

https://github.com/MessageHandler/MessageHandler.Runtime/tree/master/src/runtime/Container

Needs to be moved to 

https://github.com/MessageHandler/MessageHandler.Runtime/tree/master/src/container

**Comment by SeanFeldman** [comment]
If loading `MessageHandler.Runtime\src\container\MessageHandler.Runtime.Container.csproj`, it automatically resolves solution file found in `MessageHandler.Runtime\src\MessageHandler.Runtime.sln`.

**Comment by SeanFeldman** [comment]
Workaround: rename/remove `.sln` file during conversion.
@yvesgoeleven `Container` requires `MessageHandler.Runtime.ConfigurationSettings`. Is that covered by #8 ?

**Comment by yvesgoeleven** [comment]
Leave it all in one .sln for now, will split out in multiples (and multiple repo's) at a later stage

**Comment by yvesgoeleven** [comment]
> Container requires MessageHandler.Runtime.ConfigurationSettings. Is that covered by #8 ?

No it's covered by this one, the container has it's own configuration extension point that logically belongs to the container component. Just take a dependency on the configuration component
